### ISSUE TITLE
AAD certificate rollover

### ISSUE THREAD

**Issue by happycamper** [matvelloso/AADNodeJWT#1]
I received an email that there are periodic rollovers on AAD. Is this library affected by those?

**Comment by matvelloso** [comment]
Hi. To clarify, this isn't really a library, just a sample. That being said: I haven't yet tested this library with these new rollovers. In theory, it follows basic OpenID principles so as long as those are still the same, this should still work

**Comment by happycamper** [comment]
Ok, thanks for your response. I believe it will still work as well, but I wanted to verify with you.
